### ISSUE TITLE
Is there an extra parenthesis?

### ISSUE THREAD

**Issue by craigkopulsky** [carmengg/issues-lab#3]
https://github.com/carmengg/issues-lab/blob/84da7824637445d34a6b820ca1b3109f106197a9/got_issues.Rmd#L32-L33

Should the closed parenthesis on line 32 be removed so that color and show.legend arguments are both contained in aes() function?

**Comment by carmengg** [comment]
I don't think the show.legend = FALSE goes inside the aes() because it does not depend on any variables. I just ran it and it worked fine.

**Comment by carmengg** [comment]
Thanks for looking at the code so closely!
